environment       = "dev"
vpc_cidr          = "10.0.0.0/16"
subnet_cidr       = "10.0.1.0/24"
availability_zone = "ap-southeast-1a"
aws_region        = "ap-southeast-1"
instance_name     = "mae-http-instance"
instance_type     = "t3.micro"
ami_id            = "ami-00415ad0da23eebc1"